### ISSUE TITLE
Finish getHostedProfilePageRequest

### ISSUE THREAD

**Issue by thgaskell** [durango/authorize-net-cim#11]
I saw in the todo file that there are plans to finish the getHostedProfilePageRequest. Has there been any work done on it yet? Would you be open for a PR?

https://github.com/durango/authorize-net-cim/blob/ae29718128fb258c03c22df480c7d10b291b7f99/TODO.md

**Comment by durango** [comment]
Always open to a PR :) Thanks for even considering it
