### ISSUE TITLE
CreateCustomerProfileFromTransaction

### ISSUE THREAD

**Issue by mpuittinen** [durango/authorize-net-cim#13]
Hi!

In one of our customer cases, the initial credit card transaction is first done to Authorize.net and only after the successful transaction, the payment profile is created based on that transaction. i.e. I'd need an interface to the Authorize.net CIM createCustomerProfileFromTransaction call.

Since we need that ASAP, we'll work on that on a fork and let you know once we're done.

-Mikael

**Comment by durango** [comment]
https://github.com/durango/authorize-net-cim/pull/14 should close this issue thanks :+1:
