### ISSUE TITLE
transactionTypes issues

### ISSUE THREAD

**Issue by sean-hill** [durango/authorize-net-cim#8]
This library defines transaction types as

	this.transactionTypes = [
		'AuthOnly', 'AuthCapture',
		'CaptureOnly', 'PriorAuthCapture',
		'Refund', 'Void'
	];

But in the `createCustomerProfileTransaction` this line of code prevents `Refund` or `Void` requests.

    if (transactionType !== "AuthCapture" && transactionType !== "AuthOnly" && transactionType !== "CaptureOnly" && transactionType !== "PriorAuthCapture") {
		throw new Error('Invalid transactionType. Must be: AuthCapture, AuthOnly, CaptureOnly, or PriorAuthCapture');
    }

This could be fixed by this code

	if (this.transactionTypes.indexOf(transactionType) === -1) {
		throw new Error('Invalid transactionType. Must be: ' + this.transactionTypes.join(', '));
	}

@durango if this could be fixed that'd be great!

**Comment by durango** [comment]
Sorry for the delay! Things got in the way, thanks for the PR on this though. Really appreciate it.
